# ============================================================================
# pg_hba.conf - Host-Based Authentication - PostgreSQL Master
# ============================================================================

# TYPE  DATABASE    USER        ADDRESS          METHOD
local   all         all                         trust
host    all         all         127.0.0.1/32    md5

# Allow application user & replication user from Docker network
host    all             bdtuser     172.25.0.0/24    md5
host    all             postgres    172.25.0.0/24    md5
host    replication     repluser    172.25.0.0/24    md5
host    all             repluser    172.25.0.0/24    md5

# Allow Pgpool-II health check
host    all             repluser    172.25.0.20/32    trust
